# Generated by Django 5.1.1 on 2025-11-04 01:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10, null=True)),
                ('rank', models.CharField(choices=[('AM', 'Airman'), ('AW', 'Airwoman'), ('A2C', 'Airman 2nd Class'), ('AW2C', 'Airwoman 2nd Class'), ('A1C', 'Airman 1st Class'), ('AW1C', 'Airwoman 1st Class'), ('SGT', 'Sergeant'), ('SSGT', 'Staff Sergeant'), ('TSGT', 'Technical Sergeant'), ('MSGT', 'Master Sergeant'), ('SMSGT', 'Senior Master Sergeant'), ('CMSGT', 'Chief Master Sergeant'), ('2LT', 'Second Lieutenant'), ('1LT', 'First Lieutenant'), ('CPT', 'Captain'), ('MAJ', 'Major'), ('LTCOL', 'Lieutenant Colonel'), ('COL', 'Colonel'), ('BGEN', 'Brigadier General'), ('MGEN', 'Major General'), ('LTGEN', 'Lieutenant General'), ('GEN', 'General')], max_length=20)),
                ('serial', models.CharField(help_text='Serial number (6 digits for enlisted, or O-XXXXXX for officers)', max_length=20, unique=True)),
                ('office', models.CharField(choices=[('HAS', 'HAS'), ('951', '951'), ('952', '952'), ('953', '953')], max_length=10)),
                ('tel', models.CharField(help_text='+639XXXXXXXXX', max_length=13, validators=[django.core.validators.RegexValidator('^\\+639\\d{9}$', 'Phone must be in format +639XXXXXXXXX')])),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='personnel/pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'db_table': 'personnel',
                'ordering': ['surname', 'firstname'],
            },
        ),
    ]
