# Generated by Django 5.1.1 on 2025-11-26 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
