# Generated by Django 5.1.1 on 2025-11-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_type', models.CharField(choices=[('personnel', 'Personnel'), ('item', 'Item')], max_length=20)),
                ('reference_id', models.CharField(help_text='Personnel ID or Item ID', max_length=100)),
                ('qr_data', models.CharField(help_text='Data encoded in QR code', max_length=255)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'db_table': 'qr_codes',
                'ordering': ['-created_at'],
                'unique_together': {('qr_type', 'reference_id')},
            },
        ),
    ]
