# Generated by Django 5.1.1 on 2025-11-04 07:04

import qr_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeimage',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=qr_manager.models.qr_upload_path),
        ),
    ]
