# Generated by Django 5.1.1 on 2025-11-26 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Default', 'Compact', 'Large')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this configuration')),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210 × 297 mm)'), ('Letter', 'US Letter (8.5 × 11 in)'), ('Legal', 'US Legal (8.5 × 14 in)')], default='A4', max_length=10)),
                ('page_margin_mm', models.IntegerField(default=15, help_text='Margin around the page in millimeters (5-50mm)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)])),
                ('qr_size_mm', models.IntegerField(default=30, help_text='QR code size in millimeters (10-100mm). Recommended: 20-40mm for good quality', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('card_width_mm', models.IntegerField(default=70, help_text='Width of each QR card in millimeters (30-200mm)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('card_height_mm', models.IntegerField(default=90, help_text='Height of each QR card in millimeters (40-250mm)', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(250)])),
                ('card_padding_mm', models.IntegerField(default=3, help_text='Internal padding inside cards in millimeters (0-20mm)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('cards_per_row', models.IntegerField(default=3, help_text='Number of cards per row (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('horizontal_gap_mm', models.IntegerField(default=15, help_text='Horizontal spacing between cards in millimeters (0-50mm)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('vertical_gap_mm', models.IntegerField(default=15, help_text='Vertical spacing between cards in millimeters (0-50mm)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('font_size_id', models.IntegerField(default=11, help_text='Font size for ID text (6-24pt)', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(24)])),
                ('font_size_name', models.IntegerField(default=12, help_text='Font size for name text (6-24pt)', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(24)])),
                ('font_size_badge', models.IntegerField(default=10, help_text='Font size for badge text (6-20pt)', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)])),
                ('card_border_width', models.FloatField(default=2.0, help_text='Card border width in points (0-10pt)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('card_border_radius', models.IntegerField(default=4, help_text='Card border radius in points (0-20pt)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('is_active', models.BooleanField(default=False, help_text='Use this configuration as default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Print Configuration',
                'verbose_name_plural': 'Print Configurations',
                'ordering': ['name'],
            },
        ),
    ]
