# Generated by Django 5.1.1 on 2025-11-04 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('M14', 'M14 Rifle'), ('M16', 'M16 Rifle'), ('M4', 'M4 Carbine'), ('GLOCK', 'Glock Pistol'), ('45', '.45 Pistol')], max_length=20)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Damaged', 'Damaged')], default='Good', max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Issued', 'Issued'), ('Maintenance', 'Maintenance'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
                'ordering': ['item_type', 'serial'],
            },
        ),
    ]
