# Generated by Django 5.1.1 on 2025-11-04 01:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('Take', 'Take/Withdraw'), ('Return', 'Return')], max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mags', models.IntegerField(blank=True, default=0, help_text='Number of magazines issued', null=True)),
                ('rounds', models.IntegerField(blank=True, default=0, help_text='Number of rounds issued', null=True)),
                ('duty_type', models.CharField(blank=True, help_text='Purpose/duty type for withdrawal', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.item')),
                ('personnel', models.ForeignKey(db_column='personnel_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='personnel.personnel')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date_time'],
                'indexes': [models.Index(fields=['-date_time'], name='transaction_date_ti_ed182c_idx'), models.Index(fields=['personnel', '-date_time'], name='transaction_personn_9c3a19_idx'), models.Index(fields=['item', '-date_time'], name='transaction_item_id_c52aca_idx')],
            },
        ),
    ]
