"""
PDF Filler Utility
Handles filling PDF forms with transaction and QR data
"""
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from io import BytesIO
from django.http import HttpResponse
import os


class PDFFiller:
    """PDF form filler for transaction documents"""
    
    def __init__(self):
        self.buffer = BytesIO()
        self.canvas = canvas.Canvas(self.buffer, pagesize=letter)
        self.width, self.height = letter
    
    def create_transaction_form(self, transaction):
        """Create a transaction form PDF"""
        # Header
        self.canvas.setFont("Helvetica-Bold", 16)
        self.canvas.drawString(1*inch, self.height - 1*inch, "ARMGUARD TRANSACTION FORM")
        
        # Transaction Details
        self.canvas.setFont("Helvetica", 12)
        y_position = self.height - 1.5*inch
        
        # Transaction ID
        self.canvas.drawString(1*inch, y_position, f"Transaction ID: {transaction.id}")
        y_position -= 0.3*inch
        
        # Date and Time
        self.canvas.drawString(1*inch, y_position, f"Date/Time: {transaction.date_time.strftime('%d/%m/%Y %H:%M:%S')}")
        y_position -= 0.3*inch
        
        # Action
        self.canvas.drawString(1*inch, y_position, f"Action: {transaction.action}")
        y_position -= 0.5*inch
        
        # Personnel Information
        self.canvas.setFont("Helvetica-Bold", 12)
        self.canvas.drawString(1*inch, y_position, "Personnel Information:")
        y_position -= 0.3*inch
        
        self.canvas.setFont("Helvetica", 11)
        if transaction.personnel:
            self.canvas.drawString(1.2*inch, y_position, f"ID: {transaction.personnel.personnel_id}")
            y_position -= 0.25*inch
            self.canvas.drawString(1.2*inch, y_position, f"Name: {transaction.personnel.full_name}")
            y_position -= 0.25*inch
            self.canvas.drawString(1.2*inch, y_position, f"Rank: {transaction.personnel.rank}")
        y_position -= 0.5*inch
        
        # Item Information
        self.canvas.setFont("Helvetica-Bold", 12)
        self.canvas.drawString(1*inch, y_position, "Item Information:")
        y_position -= 0.3*inch
        
        self.canvas.setFont("Helvetica", 11)
        if transaction.item:
            self.canvas.drawString(1.2*inch, y_position, f"Serial: {transaction.item.serial}")
            y_position -= 0.25*inch
            self.canvas.drawString(1.2*inch, y_position, f"Type: {transaction.item.item_type}")
            y_position -= 0.25*inch
            self.canvas.drawString(1.2*inch, y_position, f"Model: {transaction.item.model}")
        y_position -= 0.5*inch
        
        # Remarks
        if transaction.remarks:
            self.canvas.setFont("Helvetica-Bold", 12)
            self.canvas.drawString(1*inch, y_position, "Remarks:")
            y_position -= 0.3*inch
            self.canvas.setFont("Helvetica", 11)
            self.canvas.drawString(1.2*inch, y_position, transaction.remarks)
        
        # Footer
        self.canvas.setFont("Helvetica", 9)
        self.canvas.drawString(1*inch, 1*inch, "Generated by ArmGuard System")
        
        self.canvas.showPage()
        self.canvas.save()
        
        return self.buffer.getvalue()
    
    def create_qr_label(self, qr_code):
        """Create a printable QR code label"""
        # QR Code Label
        self.canvas.setFont("Helvetica-Bold", 14)
        self.canvas.drawString(1*inch, self.height - 1*inch, f"QR Code: {qr_code.reference_id}")
        
        # QR Type
        self.canvas.setFont("Helvetica", 12)
        self.canvas.drawString(1*inch, self.height - 1.3*inch, f"Type: {qr_code.get_qr_type_display()}")
        
        # QR Data
        self.canvas.drawString(1*inch, self.height - 1.6*inch, f"Data: {qr_code.qr_data}")
        
        # Note: Actual QR image would be drawn here using drawImage
        # This requires the image path
        if qr_code.qr_image:
            try:
                self.canvas.drawImage(
                    qr_code.qr_image.path,
                    1*inch,
                    self.height - 4*inch,
                    width=2*inch,
                    height=2*inch
                )
            except:
                self.canvas.drawString(1*inch, self.height - 2*inch, "[QR Image]")
        
        self.canvas.showPage()
        self.canvas.save()
        
        return self.buffer.getvalue()
